version: '2'
services:
  rbd-driver:
    privileged: true
    network_mode: host
    image: stmops/rancher-rbd:release-v0.1.0
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
    environment:
      RANCHER_DEBUG: '${RANCHER_DEBUG}'
      RBD_MONITOR_IPS: '${RBD_MONITOR_IPS}'
      RBD_POOL: '${RBD_POOL}'
      RBD_USER_NAME: '${RBD_USER_NAME}'
      RBD_SECRET: '${RBD_SECRET}'
      RBD_IMAGE_SIZE: '${RBD_IMAGE_SIZE}'
      RBD_IMAGE_FEATURE: '${RBD_IMAGE_FEATURE}'
    volumes:
    - /run:/run
    - /var/run:/var/run
    - /dev:/host/dev
    - /lib/modules:/lib/modules:ro
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
